[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "the_rover"
version = "0.1.1-alpha"
dependencies = [
    "gpiozero",
    "pigpio",
    "keyboard",
    "fabric",
]

[project.scripts]
rover = "the_rover:__main__"
